### ISSUE TITLE
Cannot open applications which already open and minimized in tray

### ISSUE THREAD

**Issue by NoahDragon** [appetizermonster/hain#173]
Hi,

If I have an application opened, but minimized in tray, it couldn't be popup via Hain.

I think this could be an improvement for Hain.

Thank you,
Abner

**Comment by gqukyo** [comment]
Works fine for me, what applications are you referring to?  Can you give an example of a program that comes with Windows or we can download freely to test?

**Comment by NoahDragon** [comment]
@gqukyo Sure, I just tried the [1Clipboard](http://1clipboard.io/), you can use it as a test case. Moreover, I'm using the Windows 8.1.

**Comment by gqukyo** [comment]
I just tried it and it's as you stated.  However I don't think 1Clipboard is designed to be pulled up by the programs like Hain and Launchy.  The 1Clipboard app is designed to be in the background until you bring it up via the shortcut key.  Running the program via the .lnk file just tells it to launch the process but since the process is already there, it does nothing.  I am curious as to why you would use Hain or similar to bring it up when there's a shortcut key.

Btw, I've been looking for a clipboard program like this.  Thanks so much for pointing me to it!  :)

**Comment by NoahDragon** [comment]
@gqukyo  my bad, the 1Clipboard is not a good sample, as it is the first app I used to prove my issue when you asked. Do you happen to have [Evernote](https://evernote.com/) application installed? It also has the same issue.

**Comment by gqukyo** [comment]
I actually think I know what you're referring to and my understand of launchy and hain is that they are launchers for the most part so it's more or less the same as if we double clicked on a program to open it.  Not sure if hain or similar programs can add the functionality to bring up programs that are already running to the front.  Personally I'd use hain just to launch programs and alt+tab to switch between them.  If hain supports pulling up opened apps to the front and center, it'd probably require some additional syntax which to me would not be as efficient as me alt tabbing but that's just me.  :)
